---
title: Verrassing! animatie
hero_image: images/banner.png
description: Maak een animatie van een verhaal met een verrassing
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - title: Inleiding
  - title: Creëer je scène
  - title: Toon nieuwsgierigheid
    completion:
      - engaged
  - title: Voeg een verrassing toe!
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Deel en speel
  - title: Wat kun je verder nog doen?
