title: Surprise Story
hero_image: images/banner.png
description: Create a story animation with a surprise. 
version: 4
listed: false
copyedit: false
last_tested: "2021-03-09"
steps:
  - title: Introduction
  - title: Setup
  - title: Curiosity
  - title: Surprise
  - title: Reaction
  - title: Reflection
  - title: Upgrade your project
  - title: Share
  - title: What next?
