---
title: Surprise! animation
hero_image: images/banner.png
description: Create an animation of a story with a surprise
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
- title: Introduction
- title: Setup
- title: Curiosity
  completion:
  - engaged
- title: Surprise
- title: Reaction
  completion:
  - internal
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: Upgrade your project
- title: Share
- title: What next?
