---
title: サプライズ！アニメーション
hero_image: images/banner.png
description: 驚きのあるストーリーのアニメーションを作成する
meta_title: 子どもや十代の若者向けのScratchコーディングプロジェクト | サプライズ！アニメーション
meta_description: 子どもや十代の若者向けのRaspberry Pi Foundationのコーディングプロジェクトで、Scratchのコーディングを学びましょう。楽しいサプライズのあるScratchアニメーションを作ります。
pdf: resources/surprise-animation.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: はじめに
  - 
    title: 場面を作る
  - 
    title: 好奇心を示す
    completion:
      - engaged
  - 
    title: サプライズを加える！
    completion:
      - internal
  - 
    title: ふりかえり
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: プロジェクトをアップグレードする
  - 
    title: 共有して遊ぶ
