---
title: "Surpresa! animação"
hero_image: images/banner.png
description: Crie a animação de uma história com uma surpresa
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - 
    title: Introdução
  - 
    title: Configurar
  - 
    title: Curiosidade
    completion: engaged
  - 
    title: Surpresa
  - 
    title: Reação
    completion: internal
  - 
    title: Reflexão
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Melhore o seu projeto
    completion: external
  - 
    title: Compartilhar
  - 
    title: O que vem depois?
