---
title: Surpresa! animação
hero_image: images/banner.png
description: Crie a animação de uma história com uma surpresa
meta_title: Projetos de programação Scratch para crianças e adolescentes | Animação, Surpresa!
meta_description: Aprenda a codificar no Scratch com os projetos de codificação da Fundação Raspberry Pi para crianças e adolescentes. Faça uma animação no Scratch com uma surpresa divertida.
pdf: resources/surprise-animation.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Introdução
  - 
    title: Crie o o seu cenário
  - 
    title: Mostre curiosidade
    completion:
      - engaged
  - 
    title: Adicione uma surpresa!
    completion:
      - internal
  - 
    title: Teste rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - internal
  - 
    title: Melhore o seu projeto
  - 
    title: Compartilhe e brinque
