---
title: animace Překvapení!
hero_image: images/banner.png
description: Vytvoř animaci příběhu s překvapením
meta_title: Kódovací projekty ve Scratchi pro děti a náctileté | animace Překvapení!
meta_description: Nauč se kódovat ve Scratch s projekty Raspberry Pi Foundation pro děti a dospívající. Vytvoř animaci Scratch se zábavným překvapením.
pdf: resources/surprise-animation.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Úvod
  - 
    title: Vytvoř svou scénu
  - 
    title: Ukaž zvídavost
    completion:
      - engaged
  - 
    title: Přidej překvapení!
    completion:
      - internal
  - 
    title: Rychlý kvíz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Vylepši si projekt
  - 
    title: Sdílej a hraj
