---
title: "¡Sorpresa! animación"
hero_image: images/banner.png
description: Crea una animación de una historia con una sorpresa
version: 4
listed: true
copyedit: false
last_tested: "2021-03-09"
steps:
  - 
    title: Introducción
  - 
    title: Configuración
  - 
    title: Curiosidad
    completion: engaged
  - 
    title: Sorpresa
  - 
    title: Reacción
    completion: internal
  - 
    title: Reflexión
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
