---
title: '¡Sorpresa! animación'
hero_image: images/banner.png
description: Crea una animación de una historia con una sorpresa
meta_title: Proyectos de codificación de Scratch para niños y adolescentes | ¡Sorpresa! animación
meta_description: Aprende a codificar en Scratch con los proyectos de codificación de la Fundación Raspberry Pi para niños y adolescentes. Haz una animación de una historia con una sorpresa.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Introducción
  - 
    title: Crea tu escena
  - 
    title: Muestra curiosidad
    completion:
      - engaged
  - 
    title: '¡Añade una sorpresa!'
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte y juega
