---
title: مفاجئة! الرسوم المتحركة
hero_image: images/banner.png
description: قم بإنشاء رسم متحرك لقصة بمفاجأة
meta_title: مشاريع البرمجة باستخدام منصة سكراتش للأطفال والمراهقين |مفاجأة! الرسوم المتحركة
meta_description: تعلم البرمجة في سكراتش باستخدام مشاريع البرمجة الخاصة بمؤسسة Raspberry Pi مؤسسة للأطفال والمراهقين. أنشئ رسومًا متحركة وألعابًا وتطبيقات من سكراتش والمزيد.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: المقدمة
  - 
    title: اصنع مشهدك
  - 
    title: فضول
    completion:
      - engaged
  - 
    title: أضف مفاجأة!
    completion:
      - internal
  - 
    title: اختبار سريع
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: قم بترقية مشروعك
  - 
    title: شارك والعب
  - 
    title: ما التالي؟
