---
title: Överraskning! animering
hero_image: images/banner.png
description: Skapa en animation av en berättelse med en överraskning
meta_title: Scratch coding projects for kids and teens | Surprise! animation
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with a fun surprise.
pdf: resources/surprise-animation.pdf
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Inledning
  - 
    title: Skapa din scen
  - 
    title: Visa nyfikenhet
    completion:
      - engaged
  - 
    title: Lägg till en överraskning!
    completion:
      - internal
  - 
    title: Snabbt quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uppgradera ditt projekt
  - 
    title: Dela och spela
