---
title: Animation Surprise !
hero_image: images/banner.png
description: Créer une animation d'une histoire avec une surprise
meta_title: Scratch coding projects for kids and teens | Surprise! animation
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with a fun surprise.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Introduction
  - 
    title: Créer ta scène
  - 
    title: Montrer de la curiosité
    completion:
      - engaged
  - 
    title: Ajouter une surprise !
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Partager et jouer
  - 
    title: Et ensuite ?
