---
title: Surprise! animation
hero_image: images/banner.png
description: Create an animation of a story with a surprise
meta_title: Scratch coding projects for kids and teens | Surprise! animation
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with a fun surprise.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - 
    title: Introduction
  - 
    title: Create your scene
  - 
    title: Show curiosity
    completion:
      - engaged
  - 
    title: Add a surprise!
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share and play
  - 
    title: What next?
