---
title: Sorpresa! animazione
hero_image: images/banner.png
description: Crea un'animazione di una storia con una sorpresa
meta_title: Progetti di programmazione con Scratch per bambini e ragazzi | Sorpresa! animazione
meta_description: Impara a programmare con Scratch con i progetti di programmazione per bambini e ragazzi offerti dalla Raspberry Pi Foundation. Crea un'animazione Scratch con una sorpresa divertente.
version: 4
listed: true
copyedit: false
last_tested: '2021-03-09'
steps:
  - title: Introduzione
  - title: Crea la tua scena
  - title: Mostra curiosità
    completion:
      - engaged
  - title: Aggiungi una sorpresa!
    completion:
      - internal
  - title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Migliora il tuo progetto
  - title: Condividi e gioca
  - title: E adesso?
